# Book settings
title: ""
author: Neal Caren
logo: images/REALWORLD7_FIG02_CO.jpg
email: neal.caren@unc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Course materials for SOCI 101 at the UNC-CH.


latex:
  latex_documents:
    targetname: book.tex
