# Book settings
title: ""
author: Neal Caren
logo: images/walkers.png
email: neal.caren@unc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Course materials for SOCI 101 at the UNC-CH.


latex:
  latex_documents:
    targetname: book.tex

html:
  extra_navbar: ""
  extra_footer: "University of North Carolina, Chapel Hill"

repository:
  wurl: https://github.com/nealcaren/SOCI101
